services:
  sql:
    image: mysql:8.0.17
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'test'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - type: bind
        source: Data/
        target: /var/lib/mysql
      - type: bind
        source: Setup/mysqld.cnf
        target: /etc/mysql/conf.d/mysqld.cnf
      - type: bind
        source: Setup/db-setup.sql
        target: /docker-entrypoint-initdb.d/0_init.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'


