services:
  database: 
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      #MYSQL_USER: 'test'
      # You can use whatever password you like
      #MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./Data:/var/lib/mysql
      - ./Setup/mysqld.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./Setup/db-setup.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306:3306
